### ISSUE TITLE
no visible close button on mobile without implementing a button

### ISSUE THREAD

**Issue by foerever** [robinparisi/tingle#63] opened 2017-08-28 04:13 UTC
Tingle under per say 400px width will by default have a close button above the modal and it's really nice because I don't want to add a close button within the modal. This, however, disappears on my iphone under the exact same dimensions on my computer.

**Comment by robinparisi** [comment] 2017-09-22 16:53
Probably a duplicate of #42

**Closed by robinparisi** 2017-09-22 16:53 UTC
