### ISSUE TITLE
Modal close animation

### ISSUE THREAD

**Issue by ghost** [robinparisi/tingle#50] opened 2017-05-02 02:59 UTC
Thanks for this wonderful library.

How would I add a small animation, so the modal closes softly, as it does when it opens? I find it slightly inharmonious as of now.

Many thanks in advance.

**Comment by 20Fourteen** [comment] 2017-05-04 17:08
Any update or help available?

**Comment by robinparisi** [comment] 2017-05-04 19:14
Hi @20Fourteen,

This is not possible for the moment because the closing event remove tingle from the dom immediately (using display: none).

I will take a look a this when I will have some free time.

**Comment by 20Fourteen** [comment] 2017-05-04 19:45
Thank you. That's fine for me.

I wanted to know if this is possible with the current code. Now this changes to a feature request , let me know if you'll consider it when you have time.

Best regards.

**Comment by 20Fourteen** [comment] 2017-05-24 16:45
Thank you! I'll have a look and see how this works out.

**Comment by dr0bz** [comment] 2019-03-14 11:12
> Hi @20Fourteen,
> 
> This is not possible for the moment because the closing event remove tingle from the dom immediately (using display: none).
> 
> I will try to take a look at this when I will have some free time.

Hi @robinparisi ,
i've just created a pr with a fix for this. 
For the others before the issue is fixed it's possible to use the following workaround:
```
(function(close) {
    tingle.modal.prototype.close = function(force) {
        force = typeof force === 'boolean' ? force : undefined;
        close.call(this, force);
    };
}(tingle.modal.prototype.close));
```
Just execute it before `new tingle.modal()`.
Additionally take a look at the transition of .tingle-modal. It should have something like:
```
    transition: visibility .2s ease, opacity .2s ease;
```

Best regards,
dr0bz

**Comment by ivoduarte** [comment] 2019-11-29 16:24
Hello

Excelent work by the way.

I´m trying to make the close smooth transittion work on a prestashop, and it simply does not work, i´ve tried replacing the modules tingle.min.css and tingle.min.js withe this new version and made the sugested changes on #50 but the close animation is not working.

I´ve noticed that it also does not work on this demos page -> https://tingle.robinparisi.com/

Any fix for this?

Best Regards

**Comment by dr0bz** [comment] 2019-11-29 16:36
Hey @ivoduarte ,

there are to options: 

- first try out my branch https://github.com/dr0bz/tingle/tree/50-close-fix
- if you would create a CodePen (or what you prefer) example, i could look at it:)

Best regards

**Comment by ivoduarte** [comment] 2019-11-29 18:45
> Hey @ivoduarte ,
> there are to options:
> 
> first try out my branch https://github.com/dr0bz/tingle/tree/50-close-fix
> if you would create a CodePen (or what you prefer) example, i could look at it:)
> 
> Best regards

Hello @dr0bz 

Perfect, it works, how did i miss that :)

Thanks friend

Best Regards

**Closed** 2021-03-13 23:36 UTC
Labels: enhancement

**Comment by coxy17** [comment] 2024-09-14 19:10
I managed to make it work but I used the destroy() option with a setTimeout. My Tingle modal is called 'dcTableModal' and i set my timer to match the animation e.g. 500

```
beforeClose: function() {
	dcTableModal.modalBox.classList.remove('slide-right');
	setTimeout(function () {
		var modal = dcTableModal.opts;
		dcTableModal.destroy();
		dcTableModal = new tingle.modal(modal);
		return true;
	}, 500);
	return true;
}
```
